### ISSUE TITLE
Don't create own virtualenv

### ISSUE THREAD

**Issue by Sacro** [anisotropi4/woodpecker#1]
Some of us create our own environments, maybe check `$VIRTUAL_ENV` before attempting creation of one.

**Comment by anisotropi4** [comment]
I would welcome you thoughts on why this is a bad thing. Other than saying "it's bad". 

I run a whole load of environments and have found it to be good practice to decouple the dependencies and installation from these other environments. Noting that I've lost a lot of time in the past trying to fix subtle `venv` dependency bugs.

There is a lot of flux in the `pysal`, `GeoPandas` and `pyogrio` modules where in previous iterations I've had to pin package versions and even a local install of the `pysal` `momepy` module as the current one does (or at least didn't) work with the latest version of `Shapely`.

Do you want me to hack a `run-no-install.sh` or some-such run script? Noting that if it breaks you'd get to keep the pieces.

**Comment by Sacro** [comment]
I personally don't expect projects to tell me how to manage my own python install, I personally use pyenv and my virtualenvs are in `~/.pyenv/versions`, not under actual projects. 

Yes, `venv` is a pain, I've been using `poetry` recently and that's ... different, Python has too many choices!

Maybe using git submodules to manage revisions might be an idea? 

You could, I might do some pull requests myself, see if I can throw it all into Docker as well.

**Comment by anisotropi4** [comment]
I like projects to "just work": that manage dependencies and have a version that just does what it say it does. It would appear that you don't.

As package maintainer I don't see this as an issue. This is about "how" rather than "what" and will politely ask to agree to disagree with you here. Your personal preference is not mine. 

Please feel free to fork and submit an update if you want it to work that way. I'll have a look and see if it works for me. 

Or branch and manage dependencies to suit yourself. Or even just run the scripts from the command line in sequence. The python dependencies are in the `requirements.txt` file and the node is simply:

    $ npm install mapshaper --prefix node
 
Or wherever you wish to install the `mapshaper` module. Although were this to break it'll be over to you.
