### ISSUE TITLE
Don't forcibly install / uninstall NVM, ship a package.json instead

### ISSUE THREAD

**Issue by Sacro** [anisotropi4/woodpecker#2]
Some of us already have node installed and don't want things installing/uninstalling versions.

Instead just ship a package.json that requires the specific versions (if any) and that can contain the dependencies.

**Comment by anisotropi4** [comment]
Some of us don't as on my environment this is the only place I use note.

As it see it the requirements are:
1. test to see if node is installed
2. if it isn't install the local segregated node/nvm in the jay subdirectory
3. install the simplify-xl dependencies
4. run the simplify helper scripts

As I don't use node, know how to do 1 and 2 and don't know what a `package.json` is I'm stuck and would be open to suggestions how to fix this

**Comment by Sacro** [comment]
You can test in bash using `if type node &>/dev/null; then ; ... ; fi` but that might be an issue on distributions that call it `nodejs` instead. 

If it isn't there, I would expect people to be able to install it themselves, or have a flag to install via NVM. 

`package.json` is the file that contains the dependencies and scripts and such in a Node project. A little similar to a combination of `requirements.txt` and `setup.py` (I think)

**Comment by anisotropi4** [comment]
As discussed in issue #1 I think this is a difference of opinion.

For me, an issue could be
1. the code doesn't work as expected
2. the code would be better if it does x

If it is option 1 then mea culpa and I'll try and fix the issue. Despite the appearance of much of this, there has been a reasonable amount of effort put into developing and testing this stuff. But I'm not a coder, the last time I got to paid to write code was arguably in 2001 and that would have been in Visual C++, SQL and/or common lisp.

If it is option 2 then ask, I'll have a look and if I agree it is a cool thing to do then I'll have at it.If it is option 2 and it is not cool, then I would welcome your help in the form of a patch to fix the issue but I'll pass.

I have limited time and if it a choice between yak-shaving project dependencies because it's the wrong shade of green, or working on my backlog of cool data visualisations you can probably guess what I'm going to choose.

As this is very "option 2 not cool" I'm going to close this and await events. Feel free to  patch.
